//
// Created by naama on 14/01/2020.
//

#ifndef BOOST_ECHO_CLIENT_MASTER_STOMPBOOKCLUBCLIENT_H
#define BOOST_ECHO_CLIENT_MASTER_STOMPBOOKCLUBCLIENT_H


class StompBookClubClient {

    int main();

private:

};


#endif //BOOST_ECHO_CLIENT_MASTER_STOMPBOOKCLUBCLIENT_H
